import Head from "next/head";
import Card from "../components/card/Card";
import { Container, Header, Content, Grid, Row, Col, Affix } from "rsuite";
import TuriviusHeader from "../components/layout/Header";
import FilterCard from "../components/filter/FilterCard";

export default function Home(props) {
  const { cards, entities } = props;

  const data = cards.map((card) => {
    let [court] = entities.filter((item) => item.id == card.entity);
    return {
      ...card,
      entity: court.name,
    };
  });

  return (
    <div>
      <Head>
        <title>Turivius Frontend Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        <TuriviusHeader />
      </Header>

      <Container>
        <Content>
          <FilterCard />
        </Content>
        <Content>
          <Grid fluid>
            <Row>
              {data.map((card, index) => (
                <Col key={index} sm={24}>
                  <Card {...card} key={index} />
                </Col>
              ))}
            </Row>
          </Grid>
        </Content>
      </Container>
    </div>
  );
}

Home.getInitialProps = async () => {
  const cards = await (await fetch("http://localhost:3000/api/cards")).json();
  const entities = await (
    await fetch("http://localhost:3000/api/entities")
  ).json();

  return {
    cards,
    entities,
  };
};
